BEGIN TRANSACTION;

DELETE FROM material_files WHERE material_id IN (
  'seed-id-card',
  'seed-graduation-cert',
  'seed-degree-cert',
  'seed-xuexin-degree-record',
  'seed-xuexin-degree-verify',
  'seed-xuexin-student-verify',
  'seed-resume',
  'seed-id-photo',
  'seed-portrait-photo',
  'seed-household-book',
  'seed-party-proof',
  'seed-no-crime-proof',
  'seed-credit-report',
  'seed-social-insurance',
  'seed-signature',
  'seed-portfolio',
  'seed-undergrad-transcript',
  'seed-undergrad-admission-list',
  'seed-student-work-proof',
  'seed-student-card',
  'seed-leaving-proof',
  'seed-award-design-star',
  'seed-award-outstanding-league-cadre',
  'seed-award-scholarship',
  'seed-award-2019-scholarship',
  'seed-award-guoqing',
  'seed-award-qihangsheng',
  'seed-award-outstanding-graduate',
  'seed-award-speech-first',
  'seed-award-club-chair',
  'seed-award-college-cup',
  'seed-award-2019-sanhao',
  'seed-award-student-cadre-cert',
  'seed-award-sanhao',
  'seed-award-freshman-counselor',
  'seed-award-qihangsheng-2'
);

DELETE FROM materials WHERE id IN (
  'seed-id-card',
  'seed-graduation-cert',
  'seed-degree-cert',
  'seed-xuexin-degree-record',
  'seed-xuexin-degree-verify',
  'seed-xuexin-student-verify',
  'seed-resume',
  'seed-id-photo',
  'seed-portrait-photo',
  'seed-household-book',
  'seed-party-proof',
  'seed-no-crime-proof',
  'seed-credit-report',
  'seed-social-insurance',
  'seed-signature',
  'seed-portfolio',
  'seed-undergrad-transcript',
  'seed-undergrad-admission-list',
  'seed-student-work-proof',
  'seed-student-card',
  'seed-leaving-proof',
  'seed-award-design-star',
  'seed-award-outstanding-league-cadre',
  'seed-award-scholarship',
  'seed-award-2019-scholarship',
  'seed-award-guoqing',
  'seed-award-qihangsheng',
  'seed-award-outstanding-graduate',
  'seed-award-speech-first',
  'seed-award-club-chair',
  'seed-award-college-cup',
  'seed-award-2019-sanhao',
  'seed-award-student-cadre-cert',
  'seed-award-sanhao',
  'seed-award-freshman-counselor',
  'seed-award-qihangsheng-2'
);

INSERT INTO materials (id, name, category, aliases, tags, note, created_at, updated_at) VALUES
('seed-id-card', '身份证', '身份证明', '["居民身份证","身份证扫描件"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-graduation-cert', '毕业证', '学历学位', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-degree-cert', '学位证', '学历学位', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-xuexin-degree-record', '教育部学历证书电子注册备案表', '学信网', '["学历备案表"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-xuexin-degree-verify', '中国高等教育学位在线验证报告', '学信网', '["学位在线验证报告"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-xuexin-student-verify', '教育部学籍在线验证报告', '学信网', '["学籍在线验证报告"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-resume', '简历', '简历', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-id-photo', '一寸照', '照片', '["证件照"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-portrait-photo', '形象照', '照片', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-household-book', '户口簿', '身份证明', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-party-proof', '党员证明', '证明材料', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-no-crime-proof', '无犯罪记录证明', '证明材料', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-credit-report', '征信报告', '证明材料', '["个人信用报告"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-social-insurance', '社保证明', '证明材料', '["社保"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-signature', '签名', '其他', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-portfolio', '作品集', '其他', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-undergrad-transcript', '本科成绩单', '学历学位', '["成绩单"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-undergrad-admission-list', '本科新生录取名册', '学历学位', '["录取名册"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-student-work-proof', '学生工作证明', '证明材料', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-student-card', '电子学生证', '学历学位', '["学生证"]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-leaving-proof', '离职证明', '证明材料', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-design-star', '黑龙江省设计新星奖', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-outstanding-league-cadre', '优秀团干部', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-scholarship', '奖学金', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-2019-scholarship', '2019年奖学金', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-guoqing', '国青杯一等奖', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-qihangsheng', '起航生', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-outstanding-graduate', '优秀毕业生', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-speech-first', '演讲一等奖', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-club-chair', '社团管理部主席', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-college-cup', '学院杯优秀奖', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-2019-sanhao', '2019年三好学生', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-student-cadre-cert', '学生干部任职证书', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-sanhao', '三好学生', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-freshman-counselor', '新生辅导员证书', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000'),
('seed-award-qihangsheng-2', '起航生2', '获奖证书', '[]', '[]', '', strftime('%s','now') || '000', strftime('%s','now') || '000');

INSERT INTO material_files (id, material_id, format, file_path, original_filename, description, is_default, created_at) VALUES
('seed-file-id-card', 'seed-id-card', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/身份证/身份证_打印（新）.pdf', '身份证_打印（新）.pdf', '打印版', 1, strftime('%s','now') || '000'),
('seed-file-graduation-cert', 'seed-graduation-cert', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/毕业证/毕业证.jpg', '毕业证.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-degree-cert', 'seed-degree-cert', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/学位证/学位证.jpg', '学位证.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-xuexin-degree-record', 'seed-xuexin-degree-record', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/学信网/教育部学历证书电子注册备案表_刘俊利.pdf', '教育部学历证书电子注册备案表_刘俊利.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-xuexin-degree-verify', 'seed-xuexin-degree-verify', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/学信网/中国高等教育学位在线验证报告_刘俊利.pdf', '中国高等教育学位在线验证报告_刘俊利.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-xuexin-student-verify', 'seed-xuexin-student-verify', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/学信网/教育部学籍在线验证报告_刘俊利.pdf', '教育部学籍在线验证报告_刘俊利.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-resume', 'seed-resume', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/简历/刘俊利简历（新）.pdf', '刘俊利简历（新）.pdf', '通用版', 1, strftime('%s','now') || '000'),
('seed-file-id-photo', 'seed-id-photo', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/一寸照/一寸照.jpg', '一寸照.jpg', '通用版', 1, strftime('%s','now') || '000'),
('seed-file-portrait-photo', 'seed-portrait-photo', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/形象照/1.JPG', '1.JPG', '', 1, strftime('%s','now') || '000'),
('seed-file-household-book', 'seed-household-book', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/户口簿/本人页.jpg', '本人页.jpg', '本人页', 1, strftime('%s','now') || '000'),
('seed-file-party-proof', 'seed-party-proof', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/党员证明/党员身份证明.pdf', '党员身份证明.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-no-crime-proof', 'seed-no-crime-proof', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/无犯罪记录证明/无犯罪记录证明.pdf', '无犯罪记录证明.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-credit-report', 'seed-credit-report', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/征信报告/个人信用报告.pdf', '个人信用报告.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-social-insurance', 'seed-social-insurance', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/社保/浙江省个人社保信息查询服务.pdf', '浙江省个人社保信息查询服务.pdf', '社保证明', 1, strftime('%s','now') || '000'),
('seed-file-signature', 'seed-signature', 'PNG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/签名/签名1.png', '签名1.png', '', 1, strftime('%s','now') || '000'),
('seed-file-portfolio', 'seed-portfolio', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/作品集/本科作品集/个人作品集.pdf', '个人作品集.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-undergrad-transcript', 'seed-undergrad-transcript', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/本科成绩单/成绩单.pdf', '成绩单.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-undergrad-admission-list', 'seed-undergrad-admission-list', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/本科新生录取名册/本科新生录取名册（高清版）.pdf', '本科新生录取名册（高清版）.pdf', '高清版', 1, strftime('%s','now') || '000'),
('seed-file-student-work-proof', 'seed-student-work-proof', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/学生工作证明/社团管理部主席.jpg', '社团管理部主席.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-student-card', 'seed-student-card', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/开放大学/电子学生证.pdf', '电子学生证.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-leaving-proof', 'seed-leaving-proof', 'PDF', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/绿城文档/劳动合同及离职文档/刘俊利-离职证明.pdf', '刘俊利-离职证明.pdf', '', 1, strftime('%s','now') || '000'),
('seed-file-award-design-star', 'seed-award-design-star', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/黑龙江省设计新星奖.jpg', '黑龙江省设计新星奖.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-outstanding-league-cadre', 'seed-award-outstanding-league-cadre', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/优秀团干部.jpg', '优秀团干部.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-scholarship', 'seed-award-scholarship', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/奖学金.jpg', '奖学金.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-2019-scholarship', 'seed-award-2019-scholarship', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/2019年奖学金.jpg', '2019年奖学金.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-guoqing', 'seed-award-guoqing', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/国青杯一等奖.jpg', '国青杯一等奖.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-qihangsheng', 'seed-award-qihangsheng', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/起航生.jpg', '起航生.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-outstanding-graduate', 'seed-award-outstanding-graduate', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/优秀毕业生.jpg', '优秀毕业生.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-speech-first', 'seed-award-speech-first', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/演讲一等奖.jpg', '演讲一等奖.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-club-chair', 'seed-award-club-chair', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/社团管理部主席.jpg', '社团管理部主席.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-college-cup', 'seed-award-college-cup', 'PNG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/学院杯优秀奖(1).png', '学院杯优秀奖(1).png', '', 1, strftime('%s','now') || '000'),
('seed-file-award-2019-sanhao', 'seed-award-2019-sanhao', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/2019年三好学生、.jpg', '2019年三好学生、.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-student-cadre-cert', 'seed-award-student-cadre-cert', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/学生干部任职证书.jpg', '学生干部任职证书.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-sanhao', 'seed-award-sanhao', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/三好学生.jpg', '三好学生.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-freshman-counselor', 'seed-award-freshman-counselor', 'JPG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/新生辅导员证书.jpg', '新生辅导员证书.jpg', '', 1, strftime('%s','now') || '000'),
('seed-file-award-qihangsheng-2', 'seed-award-qihangsheng-2', 'PNG', '/Users/yang/Library/Mobile Documents/com~apple~CloudDocs/个人/鹏鹏/本科期间/获奖证书/起航生2.png', '起航生2.png', '', 1, strftime('%s','now') || '000');

COMMIT;
